### ISSUE TITLE
vue-starter as vue-cli template?

### ISSUE THREAD

**Issue by devCrossNet** [vuesion/vuesion#137]
After vue-cli RC:

- should the vue-starter be a vue-cli template?

- how can we do this?

# pros
- set up a new project with the right naming

# cons
- you need to install vue-cli

**Comment by angeliski** [comment]
Hey @devCrossNet I like to help make vue-starter as a vue-cli template. Do you believe I can move the project to template folder or create another project?
Do you think about it? Do you have any direction?

**Comment by devCrossNet** [comment]
Hey @angeliski, I don't have a direction yet because I don't know the internals of the vue-cli. I have to look into it as soon as version 3 is released.

I think the first question we have to answer is: **How would the vue-starter benefit from being a vue-cli template?**

If you have some insights, let's discuss here.

**Comment by angeliski** [comment]
Nice! I don't know the changes for version 3, I will look too.

About the question, I believe the better way to a vue boilerplate is the template path, but that depends of the main proposal of the project.
You can talk more about the proposal of the vue-starter?
It is a best practices example? It is a guideline? It is like a reference project? It is a boilerplate to fast init projects?

**Comment by devCrossNet** [comment]
I tried to express my goals for this starter in the docs: https://vue-starter.herokuapp.com/docs/introduction.html

Maybe this gives you an idea of the project

**Comment by angeliski** [comment]
Thank you @devCrossNet
I have not seen that page, thanks for sharing.
That quote:

> Use this project if you are an experienced developer who needs to deliver projects quickly with the highest possible quality.

Is the main of moving to vue template. 
Think about, you need to create a project quickly, but if you use the vue-starter you will need to rename and adjust the project for your use case, but if vue-starter is a template when you init the project all questions should be answered It is fast and right from the begining. What do you think? Do you have any Issue from change to that way?

**Comment by devCrossNet** [comment]
I think this point should go to the "pro" site for making it a template.

That's a good one 👍

**Comment by angeliski** [comment]
Hey @devCrossNet You can explain better why? Just to understand the cons

**Comment by devCrossNet** [comment]
Of course. I set up a vue-cli project with typescript and all of the stuff that the vue-starter has by default (ts-lint, cypress, testing, etc) expect of SSR. and the type checking was not as good as we have it already. also the dev server was much slower than what we have at the moment. the test-setup was not made for CSS-modules and some other things. I don't know how far we can tweak all the things in a template but overall I was not convinced by the experience.

**Comment by angeliski** [comment]
Really, not so good. Let's waiting for improvements in the vue-cli. Thanks for your explication.

**Comment by chrisvfritz** [comment]
@devCrossNet You don't necessarily have to migrate to a Vue CLI template, but I do strongly recommend building on top of Vue CLI 3's plugin-based system rather than re-inventing what it already does. You can see [vue-enterprise-boilerplate](https://github.com/chrisvfritz/vue-enterprise-boilerplate) for an example of this approach. 🙂

There are a few really huge advantages to this strategy: 

- The build config and dev environment can be upgraded as dependencies, instead of leaving users to maintain everything on their own as soon as they start a project.

- Where there's overlap with Vue CLI 3's responsibilities, but you've found an improvement, you can contribute that improvement directly into Vue CLI 3 so that the entire ecosystem can take advantage of it - not just users of the boilerplate. Plus, that also leaves less for you to maintain. 🙂 

- There's much less fragmentation in the ecosystem (and much more consolidation of best practices). We know there are a lot of different edge cases users may want to cover, which is why Vue CLI 3 is built to be fully configurable. Working with _a lot_ of different kinds of apps for various clients, I've never run into anything I wasn't able to change. However, if you do run into anything, let me know and we'll update Vue CLI. 🙂

> the type checking was not as good as we have it already

If that's true using Vue CLI 3 (e.g. creating an app with `vue create` instead of `vue init`), we welcome contributions. 🙂 

> the dev server was much slower than what we have at the moment

Again, if that's true using `vue create`, contributions are very welcome. I haven't personally noticed any performance issues in our current dev server.

> the test-setup was not made for CSS-modules and some other things

Using the latest `vue-jest` (included in `@vue/cli-plugin-unit-jest`), hacks like below are not actually necessary anymore:

```js
Vue.mixin({
  created() {
   this.$style = $style
  }
})
```

**Comment by devCrossNet** [comment]
Thank you for this input @chrisvfritz !

currently, I am working on version 2 of this project and I really struggle to find time to get into this topic besides my day job. 

If you have any docs, hints, code examples that could help me to save time in migrating this project, I would really appreciate it 👍 

The same for the contributions, most of the time it's easier to just implement it here instead of checking out other projects, create PRs and wait for a new version release. We use this project in our company frequently and it's very time critical.

I hope to get more time working on OSS soon. If this happens, I will contribute to the core components - for sure 😊

**Comment by devCrossNet** [comment]
@chrisvfritz quick question. I read through your readme.md in the enterprise boilerplate and the user still has to clone the repo instead of creating a new project with the Vue-CLI. Can you tell me why?

otherwise, from what I understand, it just boils down to use `@vue/cli-service` for linting, testing and maybe building the project. Am I right or is there something else I have to take into account?

Thanks in advance.

**Comment by chrisvfritz** [comment]
> I read through your readme.md in the enterprise boilerplate and the user still has to clone the repo instead of creating a new project with the Vue-CLI. Can you tell me why?

The main reason I opted for a clone rather than a template with `vue init` is to make it easier for people to contribute and test their contributions. Otherwise, a more complex workflow is necessary.

> from what I understand, it just boils down to use @vue/cli-service for linting, testing and maybe building the project. Am I right or is there something else I have to take into account?

I'd say the linting doesn't really have to run through `vue-cli-service`, though I still use `@vue/` packages to manage many linting dependencies. Testing is really nice-to-have though and the dev/build commands are absolutely essential to really benefit from Vue CLI 3. Otherwise, users are still stuck maintaining their own Webpack configurations.

Does that make sense?

**Comment by devCrossNet** [comment]
@angeliski version 2 of this project now provides a CLI to quickly create a project (`npx vue-starter-service create [project-name]`) and it gets rid of most of the devDependencies. The user doesn't have to care about this anymore.

Under the hood, the `vue-starter-service` is not using the `vue-cli-service` for now, but it is planned to use it later. This abstraction was a necessary step and will bring us closer to a vue-cli integration

**Comment by angeliski** [comment]
Amazing @devCrossNet!
I will check right now

**Comment by devCrossNet** [comment]
I will close this ticket since vuesion will be based on nuxt.js in the upcoming version.
