### ISSUE TITLE
revisit form validation solution

### ISSUE THREAD

**Issue by devCrossNet** [vuesion/vuesion#327]
currently, we have a version lock on vee-validate. 

We have to find a solution to upgrade to the latest version or switching out the validation logic. 

As mentioned by @tamer-mohamed we should use the default error messages provided by the validation library, **but** we have to make sure to lazy-load the locales to keep the bundle size small.

**Comment by MohitTilwani15** [comment]
As I can see you have already placed the logic of lazy loading locales in i18n plugin. 
The only problem I faced while updating the vee-validate version was in [VueSelect.vue](https://github.com/devCrossNet/vue-starter/blob/master/src/app/shared/components/VueSelect/VueSelect.vue) and [VueInput.vue](https://github.com/devCrossNet/vue-starter/blob/master/src/app/shared/components/VueInput/VueInput.vue). There is a computed property in both files called **isValid**. In that, instead of checking that `this.errors.first(this.name) === null` there should be a check `this.errors.first(this.name) === undefined` , as when there is no error for that respective field, it returns `undefined`

Also I found one more thing, as currently @input event is used in vue-select to change language. So whenever language is changed, the number of calls is increasing to fetch the same locales.

And a missing key attribute in `VueSelect.vue` for `option` element (Vue is smart in this, but linters are annoying 😅)

**Comment by devCrossNet** [comment]
@MohitTilwani15 I faced the problem that if you update everything according to the new version, all the tests fail because you have to add `{sync: false}` (I lost the link to the issue in vee-validate :-/) and this is something I don't want to add just because a library has an issue.

To the 2nd part. it's also possible to plugin vue-i18n with vee-validate in the new version. I already tested it and it works, but because of the reason above I completely deleted the branch and search for an alternative or wait till the library maintainers get it to work with vue-test-utils.

**Comment by devCrossNet** [comment]
TODO: add `blur` as the validation event in the current solution

**Comment by devCrossNet** [comment]
vee-validate 3.0 is released. let's see if it works now.
