### ISSUE TITLE
error when generating a module without vuex 

### ISSUE THREAD

**Issue by NickRossBrown** [vuesion/vuesion#404]
**Describe the bug**
Generating a module without vuex breaks application. 

**To Reproduce**
1. clone the repo
```
git clone https://github.com/vuesion/vuesion
```
2. cd directories 
```
cd vuesion
```
3.  install dependencies 
```
npm install
```
4. generate module without vuex
```
npm run generate
```
> Select -> module
> What should it be called? -> test
> Do you want routes? -> Y
> Do you want vuex? -> n

3. run dev server
```
npm run dev
```
4. Failed to compile.

> ERROR in ...vuesion/src/app/test/Test/Test.vue(26,28):
> TS2307: Cannot find module '../module'.
> No lint errors found

**Expected behavior**
generate a static page without vuex 

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser chrome
 - Version Chrome 73

**Comment by devCrossNet** [comment]
@NickRossBrown thank you for reporting.

I didn't come to a point where I covered all the cases in the templates (I only implemented the happy path). I am not quite sure which priority this issue will get. 

Sorry for the inconvenience, I hope it's not a blocker for you to remove this line in the test and run it again.

**Comment by NickRossBrown** [comment]
Not a blocker for me at all. I just want to help were I can. This repo is amazing. I would submit a pull request, but I am confused on how to implement changes to the generate script. 

* Additional notes about the Issue 

After removing that line 26, then throws an error from the beforeCreate() and prefetch hooks calling the module. Removing all those lines allows the application to run again. 


![Screen Shot 2019-05-10 at 4 25 18 PM](https://user-images.githubusercontent.com/39496805/57561470-b4cdd400-7340-11e9-9394-088ef426aef8.png)

![Screen Shot 2019-05-10 at 4 25 36 PM](https://user-images.githubusercontent.com/39496805/57561415-691b2a80-7340-11e9-8563-a060327d7a4a.png)

Removing those lines from the file located at .vuesion/generators/connected/connected.vue.hbs allows the generator script to create a working static page (which have to be added back to generate modules with vuex)

**Comment by devCrossNet** [comment]
Hey @NickRossBrown,
thank you very much! that is a big compliment and gives a lot of motivation to all of us working on that project.

I like to encourage you to contribute and create your first PR in this repository. I will point you to the parts that you have to understand in order to implement this feature.

- handlebar templates, you need to know the if-else syntax in handlebars because this is what the templates are based on (https://handlebarsjs.com/builtin_helpers.html)
- the variables you have to build your logic on can be found here: https://github.com/vuesion/packages/blob/master/packages/service/src/generators/module/index.ts (in your case it would be `wantVuex` and maybe `wantRoutes`)
- all the above can then be added to the vuesion templates for modules (https://github.com/vuesion/vuesion/tree/master/.vuesion/generators/module) and connected components (https://github.com/vuesion/vuesion/tree/master/.vuesion/generators/connected)

you might also want to read our contribution guidelines first (https://github.com/vuesion/vuesion/blob/master/.github/CONTRIBUTING.md)

If you need more information, please let me know 😊
