### ISSUE TITLE
Lint does not provide errors

### ISSUE THREAD

**Issue by jackmahoney** [vuesion/vuesion#405]
`npx vuesion lint` does not provide meaningful error messages.

This is all that I get.

```
» npx vuesion lint
✗ An error occurred.

Exit with error code: 2

Trace:
```

**Comment by devCrossNet** [comment]
hey, npx only supports the create command right now. Please use the locally installed binary in node_modules/.bin directory for other commands. This will change in the next version.

**Comment by devCrossNet** [comment]
@jackmahoney in which context was it necessary to run the lint command via `npx`? I would like to understand if this is a common use-case.

**Comment by devCrossNet** [comment]
@jackmahoney any news on this one?

**Comment by jackmahoney** [comment]
Hi @devCrossNet sorry for the delay. I resolved this by not using npx. I might have an unusual JS approach whereby I use npx to run bin commands. I'll close now, thanks your support.

**Comment by jackmahoney** [comment]
For more context I often use a Makefile instead of package.json and invoke node bins using npx via Make instead of "npm run <script-name>"

**Comment by devCrossNet** [comment]
@jackmahoney good to know 🙂 the thing with npx is that it doesn’t give the binary you run access to other binaries because of security reasons. The vuesion service in the current version is only a proxy to other clis which is exactly what doesn’t work with npx. In the next version it will work with the package apis instead of the binaries than it should also work for you.

**Comment by jackmahoney** [comment]
Thanks @devCrossNet I appreciate it!

**Comment by devCrossNet** [comment]
@jackmahoney I just saw on your website that you worked at Atfarm. I work at BCGDV! 😊
