### ISSUE TITLE
Error Response

### ISSUE THREAD

**Issue by itgelo** [vuesion/vuesion#479]
await HttpService.post<ISignin>('/signin', data);
how to  catch error response data?

I have tried error.response but the result is undefined

**Comment by devCrossNet** [comment]
hey @itgelo,

did you try:

```
try {
  await HttpService.post('/signin', data);
} catch (e) {
  console.log(e);
}
```
?

**Comment by itgelo** [comment]
I have tried.

`try {
  await HttpService.post('/signin', data);
} catch (e) {
  console.log(e.response); // response is undefined
}`

what I need, how to get an error response from API?

**Comment by devCrossNet** [comment]
@itgelo it depends a little bit on your API, for this reason, I would log out the error object and see how it is structured. instead of `console.log(e.response);` you do `console.log(e);` and then see where you can get the necessary information.

I am not 100% sure if this is a vuesion or an axios issue. But please try this approach first before I start spending time on troubleshooting.

**Comment by itgelo** [comment]
hi @devCrossNet, thanks for the response.
ok i will investigate this further.
