### ISSUE TITLE
Impossible to run npm run dev

### ISSUE THREAD

**Issue by josaphatim** [vuesion/vuesion#571]
**Describe the bug**
I'm unable to run scripts from the project.

**To Reproduce**
1. npx @vuesion/create project-name '...'
2. After installation finished i ran npm install then npm run dev '....'
3. vuesion@4.4.0 dev appears then NODE_ICU_DATA=node_modules/full-icu nuxt -o '....'
4. 'NODE_ICU_DATA' n’est pas reconnu en tant que commande interne 
ou externe, un programme exécutable ou un fichier de commandes.

I also tried to install via git clone then npm install but got same result

I have Nodejs 17 installed and npm 8.1

**Screenshots**
![Capture](https://user-images.githubusercontent.com/80334370/139394430-c60c8e10-f407-4960-aa40-2ea35af26bfd.JPG)

**Comment by Loopios7** [comment]
I have the same issue, I believe this is because `NODE_ICU_DATA=node_modules/full-icu nuxt -o` in windows will try to run NODE_ICU_DATA instead of setting the variable.
To set a variable in windows it uses `SET VAR=VALUE`.

I managed to get it running by changing the line in `package.json` to `"dev": "SET NODE_ICU_DATA=node_modules/full-icu && nuxt -o"`

**Comment by devCrossNet** [comment]
@Loopios7 can you do me the favour and try if https://www.npmjs.com/package/cross-env could be a viable option to support windows in this case? Then I will include it in the next update.
